steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t northamerica-northeast1-docker.pkg.dev/microservices-dev-434418/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'northamerica-northeast1-docker.pkg.dev/microservices-dev-434418/image-registry/orders-ms',
    ]
# options:
#   logging: CLOUD_LOGGING_ONLY  
availableSecrets:
  secretManager:
  - versionName: projects/31944738735/secrets/ORDERS_DB_URL/versions/1
    env: 'DATABASE_URL'

